"""
Computes per domain contacts for CAMSAP tubulin complexes using a mapping file
(domain_ranges.csv) that specifies start/end residue numbers for each domain in line
with AlphaFold3 residue numbering. Also computes overall contacts and pLDDT for each construct and per
residue summary (contacts / pLDDT) for each construct.

OUTPUT FILES 
-> contacts_summary.csv -> overall contacts in constructs and mean pLDDT
-> per_domain_summary.csv -> overall contacts per domain in full-length or partial constructs
and mean pLDDT
-> per_residue_summary subfolder containing seperate csv files for per-residue
contacts and per-residue pLDDT in constructs

The mapping file is generated by generate_constructs_domain_mapping.py
"""

# IMPORT LIBRARIES

import os
import sys
import csv
import argparse
import numpy as np
from Bio.PDB import MMCIFParser
from scipy.spatial import cKDTree
from collections import defaultdict
import glob

# CONFIGURATIONS

CONTACT_CUTOFF = 4.0          # Contact distance cutoff (Å)
H_BOND_CUTOFF = 3.5           # Hydrogen bond cutoff (Å)
SALT_CUTOFF = 4.0             # Salt bridge cutoff (Å)
HYDROPHOBIC = {'LEU', 'ILE', 'PHE', 'TRP', 'VAL', 'MET', 'ALA', 'GLY'}

CAMSAP_CHAIN = 'A'            # Chain ID for CAMSAP in the CIF files
TUBULIN_CHAINS = ['B', 'C', 'D', 'E'] # CHAIN IDs for tubulin in CIF files

CIF_SUFFIX = '_tubulin_complex_model' # CIF file suffix

RUN_PER_RESIDUE = True        # Output per‑residue contact files?

# LOAD MAPPING

def load_range_mapping(mapping_file):
    """
    Load CSV with columns: pattern, domain, start, end
    Returns a dict: pattern -> list of (domain, start, end)
    With 'pattern' being the construct id in lower case (e.g. "camsap1_cck")
    Exactly as written by generate_constructs_domain_mapping.py
    """
    mapping = {}
    if not os.path.exists(mapping_file):
        print(f"ERROR: Mapping file '{mapping_file}' not found.")
        print("Please generate it using generate_constructs_domain_mapping.py")
        return mapping

    with open(mapping_file, 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            if not row or row[0].startswith('#'):
                continue
            pattern = row[0].strip()
            domain = row[1].strip()
            try:
                start = int(row[2])
                end = int(row[3])
            except (ValueError, IndexError):
                print(f"WARNING: Invalid start/end for {pattern}, {domain} skipping")
                continue
            if pattern not in mapping:
                mapping[pattern] = []
            mapping[pattern].append((domain, start, end))

    print(f"Loaded {len(mapping)} construct mappings from '{mapping_file}'")
    return mapping

def get_domain_ranges(filename, mapping):
    """
    Find the domain ranges for a given filename by pattern matching.
    """
    base = os.path.basename(filename)
    if base.lower().endswith('.cif'):
        base = base[:-4]
    base_lower = base.lower()

    pattern = base_lower
    if pattern.endswith(CIF_SUFFIX):
        pattern = pattern [: -len(CIF_SUFFIX)]

    if pattern in mapping:
        return mapping[pattern]

    if base_lower in mapping:
        return mapping[base_lower]

    print(f"WARNING: No mapping found for '{pattern}' from({base})")
    return None

# CHEMICAL INTERACTIONS HELPER FUNCTION

def is_charged(residue, atom, charge_type='any'):
    residue, atom = residue.upper(), atom.upper()
    if charge_type in ('positive', 'any'):
        if residue == 'LYS' and atom == 'NZ':
            return True
        if residue == 'ARG' and atom in ('NH1', 'NH2'):
            return True
        if residue == 'HIS' and atom in ('NE2', 'ND1'):
            return True
    if charge_type in ('negative', 'any'):
        if residue == 'ASP' and atom in ('OD1', 'OD2'):
            return True
        if residue == 'GLU' and atom in ('OE1', 'OE2'):
            return True
    return False

def is_polar_atom(atom_name):
    return atom_name and atom_name[0] in {'N', 'O', 'S'}

def is_hydrophobic(resname):
    return resname.upper() in HYDROPHOBIC

def get_camsap_family(filename):
    f = filename.lower()
    if 'camsap_1' in f or 'camsap1' in f:
        return 'CAMSAP1'
    elif 'camsap_2' in f or 'camsap2' in f:
        return 'CAMSAP2'
    elif 'camsap_3' in f or 'camsap3' in f:
        return 'CAMSAP3'
    return None

# CIF PARSING

def parse_cif(cif_path):
    parser = MMCIFParser(QUIET=True)
    try:
        structure = parser.get_structure('complex', cif_path)
    except Exception as e:
        raise RuntimeError(f"MMCIFParser failed: {e}")

    model = structure[0]
    cam_atoms = []
    tubulin_atoms = []
    plddt_per_res = defaultdict(list)

    for chain in model:
        if chain.id == CAMSAP_CHAIN:
            for residue in chain:
                if residue.id[0] == ' ':
                    resnum = residue.id[1]
                    resname = residue.resname
                    for atom in residue:
                        if atom.name[0] == 'H':
                            continue
                        coord = atom.coord
                        bfactor = atom.bfactor
                        cam_atoms.append((resnum, resname, atom.name, tuple(coord)))
                        plddt_per_res[resnum].append(bfactor)
        elif chain.id in TUBULIN_CHAINS:
            for residue in chain:
                if residue.id[0] == ' ':
                    for atom in residue:
                        if atom.name[0] == 'H':
                            continue
                        coord = atom.coord
                        tubulin_atoms.append((residue.resname, residue.id[1], atom.name, chain.id, tuple(coord)))

    if not cam_atoms:
        raise RuntimeError(f"No CAMSAP chain '{CAMSAP_CHAIN}' found.")
    if not tubulin_atoms:
        raise RuntimeError(f"No tubulin chains {TUBULIN_CHAINS} found.")

    plddt = {res: np.mean(vals) for res, vals in plddt_per_res.items()}
    return cam_atoms, tubulin_atoms, plddt

# CONTACT CALCULATION

def compute_contacts(cam_atoms, tubulin_atoms):
    """
    Compute contacts between CAMSAP atoms and tubulin atoms.
    Returns: per_residue dict, total dict
    """
    # Group CAMSAP atoms by residue
    cam_residues = {}
    for resnum, resname, atom_name, coord in cam_atoms:
        if resnum not in cam_residues:
            cam_residues[resnum] = {'resname': resname, 'atoms': []}
        cam_residues[resnum]['atoms'].append((atom_name, coord))

    # Prepare tubulin data
    tub_coords = np.array([a[4] for a in tubulin_atoms])
    tub_resnames = [a[0] for a in tubulin_atoms]
    tub_atomnames = [a[2] for a in tubulin_atoms]
    tub_chains = [a[3] for a in tubulin_atoms]

    tree = cKDTree(tub_coords)

    per_res = {}
    totals = {
        'total_contacts': 0,
        'total_hbonds': 0,
        'total_salt': 0,
        'total_hydrophobic': 0,
        'total_alpha_contacts': 0,
        'total_beta_contacts': 0,
        'interface_residues': 0
    }

    for resnum, res_data in cam_residues.items():
        resname = res_data['resname']
        contacts = 0
        hbonds = 0
        salt = 0
        hydrophobic = 0
        alpha = 0
        beta = 0

        for atom_name, coord in res_data['atoms']:
            coord_arr = np.array(coord)
            indices = tree.query_ball_point(coord_arr, CONTACT_CUTOFF)
            if not indices:
                continue
            contacts += len(indices)

            for idx in indices:
                dist = np.linalg.norm(coord_arr - tub_coords[idx])

                # Alpha / beta tubulin -> if not alpha (chain B or C) then beta

                if tub_chains[idx] in ['B', 'C']:
                    alpha += 1
                else:
                    beta += 1

                # Hydrogen bond

                if is_polar_atom(atom_name) and is_polar_atom(tub_atomnames[idx]) and dist < H_BOND_CUTOFF:
                    hbonds += 1

                # Salt bridge

                if is_charged(resname, atom_name, 'positive') and is_charged(tub_resnames[idx], tub_atomnames[idx], 'negative'):
                    if dist < SALT_CUTOFF:
                        salt += 1
                if is_charged(resname, atom_name, 'negative') and is_charged(tub_resnames[idx], tub_atomnames[idx], 'positive'):
                    if dist < SALT_CUTOFF:
                        salt += 1

                # Hydrophobic contact

                if is_hydrophobic(resname) and is_hydrophobic(tub_resnames[idx]):
                    hydrophobic += 1

        if contacts > 0 or hbonds > 0 or salt > 0 or hydrophobic > 0:
            per_res[resnum] = {
                'resname': resname,
                'contacts': contacts,
                'hbonds': hbonds,
                'salt': salt,
                'hydrophobic': hydrophobic,
                'alpha_contacts': alpha,
                'beta_contacts': beta
            }
            totals['total_contacts'] += contacts
            totals['total_hbonds'] += hbonds
            totals['total_salt'] += salt
            totals['total_hydrophobic'] += hydrophobic
            totals['total_alpha_contacts'] += alpha
            totals['total_beta_contacts'] += beta

    totals['interface_residues'] = len(per_res)
    return per_res, totals

# PER DOMAIN CONTACTS USING DOMAIN MAPPING

def compute_domain_contacts(cam_atoms, tubulin_atoms, plddt, filename, mapping):
    """
    Compute contacts per domain using absolute residue ranges from the mapping file.
    """
    family = get_camsap_family(filename)
    if not family:
        max_res = max([r[0] for r in cam_atoms]) if cam_atoms else 0
        if max_res > 1500:
            family = 'CAMSAP1'
        elif max_res > 1300:
            family = 'CAMSAP2'
        else:
            family = 'CAMSAP3'
        print(f"  Inferred family '{family}' from max residue {max_res}")

    ranges = get_domain_ranges(filename, mapping)
    if not ranges:
        print(f"  No mapping found for {filename} – skipping domain decomposition")
        return None, family

    print(f"  Domain ranges: {ranges}")

    # Build domain map from ranges

    domain_map = {}
    for domain, start, end in ranges:
        domain_map[domain] = (start, end)

    # Group atoms by domain based on residue number

    domain_atoms = {domain: [] for domain in domain_map.keys()}
    unknown = 0

    for resnum, resname, atom_name, coord in cam_atoms:
        assigned = False
        for domain, (start, end) in domain_map.items():
            if start <= resnum <= end:
                domain_atoms[domain].append((resnum, resname, atom_name, coord))
                assigned = True
                break
        if not assigned:
            unknown += 1

    if unknown:
        print(f"  WARNING: {unknown} atoms not assigned to any domain")

    # Compute contacts for each domain

    domain_results = {}

    for domain, atoms in domain_atoms.items():
        if not atoms:
            domain_results[domain] = {
                'domain': domain,
                'total_contacts': 0,
                'total_hbonds': 0,
                'total_salt': 0,
                'total_hydrophobic': 0,
                'total_alpha_contacts': 0,
                'total_beta_contacts': 0,
                'interface_residues': 0,
                'domain_length': 0,
                'mean_plddt': 0.0
            }
            continue

        # Compute contacts for domains atoms

        per_res, totals = compute_contacts(atoms, tubulin_atoms)

        # Compute mean pLDDT for residues in this domain
        domain_residues_all = set([r[0] for r in atoms])
        domain_length = len(domain_residues_all)

        plddt_vals = [plddt.get(r, 0.0) for r in domain_residues_all]
        mean_plddt = np.mean(plddt_vals) if plddt_vals else 0.0

        domain_results[domain] = {
            'domain': domain,
            'total_contacts': totals['total_contacts'],
            'total_hbonds': totals['total_hbonds'],
            'total_salt': totals['total_salt'],
            'total_hydrophobic': totals['total_hydrophobic'],
            'total_alpha_contacts': totals['total_alpha_contacts'],
            'total_beta_contacts': totals['total_beta_contacts'],
            'interface_residues': totals['interface_residues'],
            'domain_length': len(per_res),
            'mean_plddt': mean_plddt,
            'per_residue': per_res
        }

    return domain_results, family

# WRITE OUTPUT FILES

def write_summary_csv(results, outfile):
    if not results:
        return

    fieldnames = [
        'file', 'camsap_length', 'interface_residues',
        'total_contacts', 'total_hbonds', 'total_salt',
        'total_hydrophobic', 'alpha_contacts', 'beta_contacts',
        'mean_plddt'
    ]

    with open(outfile, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction='ignore')
        writer.writeheader()
        for r in results:
            writer.writerow(r)

    print(f"Summary saved to {outfile}")

def write_per_domain_csv(domain_entries, outfile):
    if not domain_entries:
        print("No domain entries to write.")
        return

    fieldnames = [
        'file', 'family', 'domain', 'domain_length'
        'total_contacts', 'total_hbonds', 'total_salt',
        'total_hydrophobic', 'alpha_contacts', 'beta_contacts',
        'interface_residues', 'mean_plddt'
    ]

    rows = []
    for entry in domain_entries:
        for domain, data in entry['domains'].items():
            rows.append({
                'file': entry['file'],
                'family': entry['family'],
                'domain': domain,
                'domain_length': data['domain_length']
                'total_contacts': data['total_contacts'],
                'total_hbonds': data['total_hbonds'],
                'total_salt': data['total_salt'],
                'total_hydrophobic': data['total_hydrophobic'],
                'alpha_contacts': data['total_alpha_contacts'],
                'beta_contacts': data['total_beta_contacts'],
                'interface_residues': data['interface_residues'],
                'mean_plddt': data['mean_plddt']
            })

    with open(outfile, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"Per-domain summary saved to {outfile}")

def write_per_residue_files(results_list, outdir):
    if not RUN_PER_RESIDUE:
        return

    os.makedirs(outdir, exist_ok=True)

    for res in results_list:
        base = res['file'].replace('.cif', '')
        per = res.get('per_residue', {})

        if per:
            outfile = os.path.join(outdir, f"{base}_per_residue.csv")
            with open(outfile, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerow(['residue', 'resname', 'contacts', 'hbonds', 'salt', 'hydrophobic'])
                for n in sorted(per.keys()):
                    d = per[n]
                    writer.writerow([n, d['resname'], d['contacts'], d['hbonds'], d['salt'], d['hydrophobic']])

        plddt = res.get('plddt', {})
        if plddt:
            outfile = os.path.join(outdir, f"{base}_plddt.csv")
            with open(outfile, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerow(['residue', 'plddt'])
                for n in sorted(plddt.keys()):
                    writer.writerow([n, plddt[n]])

    print(f"Per-residue files saved to {outdir}")

# EXTRACT ALL METRICS FUNCTION

def extract_all_metrics(cif_path, output_dir, mapping):
    print(f"\nProcessing: {os.path.basename(cif_path)}")

    # Parse CIF
    cam_atoms, tubulin_atoms, plddt = parse_cif(cif_path)

    # Total contacts
    per_res, totals = compute_contacts(cam_atoms, tubulin_atoms)

    # Domain contacts
    filename = os.path.basename(cif_path)
    domain_results, family = compute_domain_contacts(cam_atoms, tubulin_atoms, plddt, filename, mapping)

    results = {
        'file': filename,
        'camsap_length': len(set(r[0] for r in cam_atoms)),
        'interface_residues': totals['interface_residues'],
        'total_contacts': totals['total_contacts'],
        'total_hbonds': totals['total_hbonds'],
        'total_salt': totals['total_salt'],
        'total_hydrophobic': totals['total_hydrophobic'],
        'alpha_contacts': totals['total_alpha_contacts'],
        'beta_contacts': totals['total_beta_contacts'],
        'mean_plddt': np.mean(list(plddt.values())) if plddt else 0.0,
        'per_residue': per_res,
        'plddt': plddt,
        'domain_results': domain_results,
        'family': family
    }

    return results

# MAIN

def main():
    parser = argparse.ArgumentParser(
        description='Calculates domain contacts based on absolute domain positions'
    )
    parser.add_argument('cif_files', nargs='*', help='CIF files to analyse')
    parser.add_argument('--mapping', default='domain_ranges.csv',
                        help='Mapping CSV with pattern,domain,start,end')
    parser.add_argument('--outdir', default='./results',
                        help='Output directory')
    parser.add_argument('--out', default='contacts_summary.csv',
                        help='Summary CSV filename')
    args = parser.parse_args()

    if not args.cif_files:
        args.cif_files = glob.glob('./cifs/*.cif')
        if not args.cif_files:
            print("No CIF files found.")
            sys.exit(1)

    mapping = load_range_mapping(args.mapping)
    if not mapping:
        print("ERROR: No mapping loaded. Please generate it first.")
        print("Run: python generate_domain_ranges_from_constructs.py --out domain_ranges.csv")
        sys.exit(1)

    os.makedirs(args.outdir, exist_ok=True)

    all_results = []
    domain_entries = []

    for cif in args.cif_files:
        res = extract_all_metrics(cif, args.outdir, mapping)
        if res:
            all_results.append(res)
            if res['domain_results'] is not None:
                domain_entries.append({
                    'file': res['file'],
                    'family': res['family'],
                    'domains': res['domain_results']
                })

    if all_results:
        write_summary_csv(all_results, os.path.join(args.outdir, args.out))
        write_per_domain_csv(domain_entries, os.path.join(args.outdir, 'per_domain_summary.csv'))
        write_per_residue_files(all_results, os.path.join(args.outdir, 'per_residue_summary'))
        print("FINISHED!")
    else:
        print("No results produced.")

if __name__ == '__main__':
    main()